[package]
name = "sss-core"
version = "0.1.0"
description = "Solana Stablecoin Standard - Core Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sss_core"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("anchor-debug"))'] }

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
pyth-solana-receiver-sdk = { workspace = true }
